### ISSUE TITLE
[Features Request] Statistics for user + Languages Option

### ISSUE THREAD

**Issue by nyxzryu** [cydrobolt/polr#217] opened 2016-09-01 02:31 UTC
How about adding a statistics page in the user dashboard ?
So the user can track from where the visitor come from. A stats page with world map option would be useful. this would be great for company purpose since they'll able to track and specify their visitor.

Also can you add language pages so admin can choose what languages they'll use ?
Just like IDM does with lang option.

**Comment by cydrobolt** [comment] 2016-09-01 02:43
Duplicate of #207?

**Comment by nyxzryu** [comment] 2016-09-01 02:52
@cydrobolt Well almost same as #207 but the languages option not :v:

**Comment by cydrobolt** [comment] 2016-09-01 08:31
We have #51 as well :)

Implementing translations would be a long process, which would need to start with converting strings and receiving translations. Closing ticket in favour of #207 and #51

**Closed by cydrobolt** 2016-09-01 08:31 UTC
