### ISSUE TITLE
Not working upgrade 2.1.1 to 2.2.0 

### ISSUE THREAD

**Issue by 023Stije** [cydrobolt/polr#424] opened 2018-03-06 10:40 UTC
Upgrade not working

## Expected Behavior

Following the upgrade should upgrade polr from 2.1.1 to 2.2.0 and have a working polr again.

## Current Behavior

Doing the upgrade / or even when installing a new version from scratch the https://url.domain/admin page is not working. I see the links but clicking on it does not work.
I do not see links https://url.domain/admin#links
I do not see settings: https://url.domain/admin#settings
I do not see admin: https://url.domain//admin#admin

## Possible Solution

No idea. Even after setting up a new polr instance it is not working.

## Context

Need to have the long link edit on my polr instance. So that is why i want to upgrade from 2.1.1 to 2.2.0

## Your Environment

* Version or latest commit hash (`git rev-parse HEAD`):2.1.1 / 753fad41d60986336592f412f1da7bb1bf8b5e47
* Environment name and version (e.g. Chrome 39, PHP 7.0, etc): PHP 5.6.32 on Ubuntu 16.04.3 / Browsers: safari 11.0.3 / chrome 64 / opera 51

**Comment by 023Stije** [comment] 2018-03-06 12:33
click on links.....i see nothing...but url is changing.

![polr](https://user-images.githubusercontent.com/34742967/37032452-de735970-2142-11e8-9090-37633c5cccdb.png)

**Comment by overint** [comment] 2018-03-27 11:54
Hey @023Stije 
Can you check the javascript console for errors?

Thanks!

**Comment by cydrobolt** [comment] 2018-05-05 21:07
This could be a duplicate of #433

Try clearing your cache and loading the admin panel again. Feel free to reopen this issue if the problem comes up again.

**Closed by cydrobolt** 2018-05-05 21:07 UTC
Labels: needs more info
