### ISSUE TITLE
Sort by click number in link list is wrong

### ISSUE THREAD

**Issue by guilro** [cydrobolt/polr#294] opened 2017-02-06 14:46 UTC
## Expected Behavior
In the link list in the admin, when you click on the heading of the  "Clicks" column, it should sort the list by number of clicks.

## Current Behavior
The list is sorted alphabetically by string representing number of clicks : 12 < 223 < 3
![capture](https://cloud.githubusercontent.com/assets/301998/22651300/e242edd6-ec82-11e6-9b15-ddcfa8f44f77.png)
 

## Possible Solution
Sort by number and not by string.

## Steps to Reproduce (for bugs)
1. create several links
2. click 12 times on one of them and twice on another
3. try to sort links by clicks

## Context
I was trying to see who had scored the best links among my colleagues.

## Your Environment
* Version 2.1.1
* Chromium 55.0.2883.87
* Instance link (optional): https://jlm17.fr

**Comment by cydrobolt** [comment] 2017-02-06 15:53
This issue seems to be caused by HTML and spaces present in addition to the integer in the table. Adding a type to the column, such as "html-num" should fix the problem. 

Will commit a fix to this problem soon.

**Comment by cydrobolt** [comment] 2017-02-06 22:23
It doesn't seem like indicating the column type on the client side solves the problem. I've opened an issue upstream at yajra/laravel-datatables to see if this issue might be caused by a problem with the server-side DataTables plugin.

**Comment by cydrobolt** [comment] 2017-02-08 01:08
It seems like the clicks field was a `string` field rather than an `integer` field. I've merged a new migration that should alter the field type to integer. Due to the Laravel DataTables plugin's SQL sorting, the string fields were not correctly sorting.

Please see http://docs.polr.me/en/latest/user-guide/upgrading/ for a guide on upgrading Polr. You will need to pull the repo and run the latest migrations to fix the problem. As always, make sure to back up your database and files before updating or running migrations.

Thank you :)

**Closed** 2017-02-08 01:07 UTC
Labels: bug
